name: CI
on:
  push:
    branches:
      - main
env:
  SPRINT: 0
  MONTH: null
  YEAR: null
  SEM: null
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  RESET: false

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
  new_branch:
    permissions: write-all
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set current year as env variable
        run: echo "YEAR=$(date +'%y')" >> $GITHUB_ENV
      - name: Set current month as env variable
        run: echo "MONTH=$(date +'%m')" >> $GITHUB_ENV

      - name: check for spring semester
        if: "${{ env.MONTH >= 1 && env.MONTH <= 8 }}"
        run: echo "SEM=s" >> $GITHUB_ENV
      - name: check for fall semester
        if: "${{ env.MONTH >= 9 && env.MONTH <= 12 }}"
        run: echo "SEM=f" >> $GITHUB_ENV
      - name: Set sprint number
        run: echo "SPRINT"=${{ env.SPRINT }}+1 >> $GITHUB_STATE
      - name: Reset sprint count at the beginning of the semester
        if: "${{ (env.MONTH == 1 || env.MONTH == 9) && (env.RESET == false) }}"
        run: echo "SPRINT"=0 >> $GITHUB_STATE
        run: echo "RESET"=true >> $GITHUB_STATE
      - name: Reset reset flag once month is over
        if: "${{ env.MONTH != 1 && env.MONTH != 9 }}"
        run: echo "RESET"=false >> $GITHUB_STATE

      - name: make new branch
        uses: peterjgrainger/action-create-branch@v2.3.0
        env:
          github_token: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: "refs/heads/sprint/${{ env.SEM }}${{ env.YEAR }}/${{ env.SPRINT }}"
          sha: '${{ github.event.pull_request.head.sha }}'
        
